import { atom } from 'jotai'
import { darkTheme } from './themes'

export const charactersResults = atom([])
export const matchingResults = atom([])
export const userInput = atom('')
export const searchHistory = atom([])
export const favoriteCharacters = atom([])
export const isSearchHistoryDisplayed = atom(false)
export const modalVisibility = atom(false)
export const handleApiError = atom(null)
export const modalCharacter = atom(null)
export const previousPageData = atom([])
export const nextPageData = atom([])
export const favoriteCardTooltip = atom(false)
export const currentPageData = atom([])
export const resultsPages = atom(null)
export const currentTheme = atom(darkTheme)
export const loadingCards = atom(true)
export const refreshPage = atom(false)